version: "3.0"
services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=muffin-wallet
      - POSTGRES_PASSWORD=muffin-wallet
      - POSTGRES_DB=muffin_wallet
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://muffin-wallet:muffin-wallet@localhost:5432/muffin_wallet?sslmode=disable"
    network_mode: host
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_2:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.min-block-duration=120s'
      - '--storage.tsdb.max-block-duration=120s'
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml


  grafana:
    ports:
      - "3000:3000"
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped

volumes:
  postgres_data:
  grafana-data:
  prometheus_data_2: