{
 "title": "muffin-wallet metrics dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество запросов в секунду по каждому методу REST API приложения без учета статуса",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(uri, method, instance) (\r\n  rate(http_server_requests_seconds_count{uri=~\"/v1/.*\"}[5m])\r\n)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду по сервисам АПИ по статусам ответа",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=~\"/v1/.*\"}[5m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Среднее количество ошибок в приложении (+статус)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(uri, status) (\r\n  rate(http_server_requests_seconds_count{uri=~\"/v1/.*\", status=~\"5..|4..|3..\"}[5m])\r\n)",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Среднее время запросов к muffin-currency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_count{uri=~\"/.*\"}[5m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Активные подключения к БД",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\", datname=\"muffin_wallet\"}) by (datname, state)",
     "legendFormat": "database={{datname}}, state={{state}}"
    }
   ]
  }
 ]
}