{
 "title": "Logs of muffin-wallet",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "detected_level", "label": "detected_level", "query": "DEBUG, INFO, WARN, ERROR" },
   {
    "name": "trace_id",
    "label": "trace_id",
    "query": "8548d5080df7728bedc52ef113e73855"
   }
  ]
 },
 "panels": [
  {
   "title": "Custom log_level",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet\"} | detected_level = `$detected_level`"
    }
   ]
  },
  {
   "title": "All muffin-wallet logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet\"} |= ``"
    }
   ]
  },
  {
   "title": "Custom traceId",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet\"} | trace_id = `$trace_id`"
    }
   ]
  },
  {
   "title": "Custom logLevel and traceId",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet\"} | trace_id = `$trace_id` | detected_level = `$detected_level`"
    }
   ]
  }
 ]
}