apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
    isDefault: false
    editable: true
    uid: ffbxenykfad4wf
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: true
    editable: true
    uid: cfb2dsbssg000b
  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://host.docker.internal:9411
    isDefault: false
    editable: true
    uid: zipkin-local
